# Generated by Django 2.2 on 2020-01-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordenador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('extra', models.CharField(blank=True, choices=[('Folguista', 'Folguista'), ('Feirista', 'Feirista')], max_length=15)),
                ('turno', models.CharField(default=True, max_length=50)),
                ('equipe', models.CharField(choices=[('RO', 'RO'), ('TARM', 'TARM')], default='TARM', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('turno', models.CharField(choices=[('NDA', 'NDA'), ('A - Madrugada', 'A - Madrugada'), ('B - Manhã', 'B - Manhã'), ('C - Tarde', 'C - Tarde'), ('D - Noite', 'D - Noite')], max_length=20, primary_key=True, serialize=False)),
                ('funcionario', models.ManyToManyField(to='coordenador.Funcionario')),
            ],
            options={
                'ordering': ['turno'],
            },
        ),
        migrations.CreateModel(
            name='PlantaoExtra',
            fields=[
                ('p_extra_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('equipe', models.CharField(choices=[('RO', 'RO'), ('TARM', 'TARM')], default='TARM', max_length=15)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plantao_extra', to='coordenador.Plantao')),
            ],
            options={
                'unique_together': {('data', 'plantao', 'equipe')},
            },
        ),
        migrations.CreateModel(
            name='Folga',
            fields=[
                ('folga_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('equipe', models.CharField(choices=[('RO', 'RO'), ('TARM', 'TARM')], default='TARM', max_length=15)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plantao_folga', to='coordenador.Plantao')),
            ],
            options={
                'unique_together': {('data', 'plantao', 'equipe')},
            },
        ),
    ]
